### ISSUE TITLE
Add splash animation to AROMA

### ISSUE THREAD

**Issue by JaredTamana** [davwheat/Wear24-NFC-ROM#17]
I'm already making a logo. Let's spice things up with an animation.
- [ ] Create initial logo
- [ ] Animate frames
- [ ] Add files to AROMA
- [ ] Edit AROMA config

**Comment by davwheat** [comment]
We want a logo first (one that we could animate on launching aroma)

**Comment by JaredTamana** [comment]
shut up and read the checklist, dav :P

**Comment by davwheat** [comment]
sorry dad
