### ISSUE TITLE
AROMA installer does not react to touch inputs

### ISSUE THREAD

**Issue by JaredTamana** [davwheat/Wear24-NFC-ROM#18]
AROMA installer doesn not respond to touch. See https://drive.google.com/file/d/1ZLLNA-3w07MlkVoHxVAe8gQui6GnlC7j/view?usp=drivesdk for example. 
- [x] Port AROMA to TWRP volume script

**Comment by JaredTamana** [comment]
AROMA may be out the window. See https://forum.xda-developers.com/android/software/guide-volume-key-selection-flashable-zip-t3773410. We will have to adapt it to Power instead of Vol +/-

**Comment by JaredTamana** [comment]
what when did dav get unassigned

*blames GK*

anyways TWRP script has been pushed to [the nfc branch](/davwheat/Wear24-NFC-ROM/nfc). Testing now.

**Comment by davwheat** [comment]
👌

**Comment by JaredTamana** [comment]
Moving to #23, keeping this issue around until AROMA remove is merged to master.

**Comment by JaredTamana** [comment]
waiting on PR to nfc, then to master
