### ISSUE TITLE
Installer script for TWRP does not start

### ISSUE THREAD

**Issue by JaredTamana** [davwheat/Wear24-NFC-ROM#24]
Installer script does not start. Likely due to syntax error.

**Comment by davwheat** [comment]
*Well ain't that just great.*

**Comment by JaredTamana** [comment]
Issue is likely a symptom of a bigger problem -- our method of patching /system is no good. For now, we will switch to manual file moving and chmodding. This will have to change in the future if we start creating bigger changes,

**Comment by JaredTamana** [comment]
Never mind, we were wrong. Building empty images probably doesn't help

**Comment by JaredTamana** [comment]
Syntax error? Let's try compiling it as a binary...

**Comment by davwheat** [comment]
https://unix.stackexchange.com/questions/64762/how-to-convert-a-shell-script-into-a-binary-executable

**Comment by JaredTamana** [comment]
We're switching to a script method eventually, currently in nfc-newbinary. This will be merged to nfc very soon
