### ISSUE TITLE
build(selinux): Build fails due to missing security context for /system/app

### ISSUE THREAD

**Issue by JaredTamana** [davwheat/Wear24-NFC-ROM#25]
`error: build_directory_structure: cannot lookup security context for /system/app`

**Comment by JaredTamana** [comment]
Fixed by bae5526

**Comment by JaredTamana** [comment]
Not fixed.

**Comment by JaredTamana** [comment]
It's an issue with our folders?????????? We can feed make_ext4fs literally any file and it will return the same error

**Comment by davwheat** [comment]
wtf m8 that's weird

**Comment by JaredTamana** [comment]
New suggestion: let's try this. https://github.com/EpicAOSP/make_ext4

**Comment by JaredTamana** [comment]
Fixed? Thanks, lerxi, yer a wizard.
