### ISSUE TITLE
Find publicly known signing keys

### ISSUE THREAD

**Issue by davwheat** [davwheat/Wear24-NFC-ROM#7]

**Comment by JaredTamana** [comment]
`The Android tree includes test-keys under build/target/product/security` https://source.android.com/devices/tech/ota/sign_builds

**Comment by davwheat** [comment]
These are only test keys though. Would they work in practise? Would it be better if we make our own keys and signed with them instead?

**Comment by JaredTamana** [comment]
They work fine. Custom ROMs use them all the time iirc. Unless we are concerned about our files being under security scrutiny, there's no reason to sign them with unique keys. Usually signing is done before building Android source. We don't have that luxury. I don't even know if we need to sign, but without signing, the META-INF folder isn't created

**Comment by davwheat** [comment]
Ok. You know waay more about this stuff than me but I just wanted to check :)

**Comment by davwheat** [comment]
Can we close?
